### ISSUE TITLE
Categoris color different on posts and changes when opening a post

### ISSUE THREAD

**Issue by wyq977** [CaiJimmy/hugo-theme-stack#71]
**Describe the bug**
The color of a category shows differently on different post and change upon clicking

**To Reproduce**
In main page
1. Go to Demo website
2. Multiple post in **Test** but they are in different colors

In archive
1. Open post in Test
2. Color of the category change for a brief moment

**Expected behavior**
Posts in the same category should show the same color for consistency

No changing color when opening a post

**Screenshots**
Screenshot on clicking on Safari macOS Catalina show change of change upon opening

https://user-images.githubusercontent.com/27303600/102659945-8b129b00-417a-11eb-8aa2-435ce2480d64.mov

https://user-images.githubusercontent.com/27303600/102660473-61a63f00-417b-11eb-965c-e6a2a66832d7.mp4

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome, safari
 - Version chrome Version 87.0.4280.88 (Official Build) (x86_64), safari: Version 14.0 (15610.1.28.1.9, 15610)

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max
 - OS: iOS 14.0
 - Browser safari

**Additional context**

**Comment by CaiJimmy** [comment]
> Posts in the same category should show the same color for consistency

Backgrounds of categories of each article are **extracted from its cover image**. Default colors are defined in `variables.scss`:

https://github.com/CaiJimmy/hugo-theme-stack/blob/e9c1abac934739ee1757569446b36b5876a62834/assets/scss/variables.scss#L1

> No changing color when opening a post

Because the colors are extracted in the frontend, that's something inevitable. I tried to accelerate that process by introducing the localStorage cache. But still, it's visible.

**Comment by wyq977** [comment]
Thx for the quick answer! Really liked the design and already using for a while. 😄 

> Because the colors are extracted in the frontend, that's something inevitable. I tried to accelerate that process by introducing the localStorage cache. But still, it's visible.

I get why there's a switch upon opening a post as the colors are being extracted.

Regarding the `defaultTagBackgrounds` I suppose that the colors of each categories are randomly chosen from one of five default values? Not quite sure why the color for a particular category would change when there's no cover image.

Like the screenshot of my test blog below, categories: **Guide**
![Screen Shot 2020-12-18 at 11 17 08 PM](https://user-images.githubusercontent.com/27303600/102666428-27db3580-4187-11eb-8922-48a7b8b34323.png)

The post containing cover image pick/extrat a color but in total three colors are being used for **Guide**

It's kind of confusing to readers visually as one might think they are in different categories

Best

**Comment by CaiJimmy** [comment]
> Regarding the defaultTagBackgrounds I suppose that the colors of each categories are randomly chosen from one of five default values? Not quite sure why the color for a particular category would change when there's no cover image.

https://github.com/CaiJimmy/hugo-theme-stack/blob/e9c1abac934739ee1757569446b36b5876a62834/assets/scss/partials/article.scss#L40-L47

Not randomly. The background of categories of the first article by default uses `$defaultTagBackgrounds[1]`, the second one `[2]`,...
Because there are only 5 default colors, the sixth article uses again `$defaultTagBackgrounds[1]`.

**Comment by wyq977** [comment]
I see Thx for the explaining!

Quite confused by that at first. 

May I ask why you would like to set same categories to different color? Personally, I feel each categories with a dedicated unique color might be more visually informative, or one could extrat color from the cover image of each categories set.

**Comment by CaiJimmy** [comment]
> May I ask why you would like to set same categories to different color?

That wasn't something done intentionally. I did that at the very first versions of this theme just because it looked good to me.

But I agree with you, each category should have its own color. That could be done by adding a new field to category setting. 

In fact, it might be a solution to that annoying "color blink", as the background is fixed while generating the site.

Or extract the color from the cover image of each category as you suggested.

**Comment by wyq977** [comment]
That'll be great! Love to see the update

I am not familar with web dev so probably could not contribute to this theme (already looking pretty look 👍 )

**Comment by CaiJimmy** [comment]
I created a PR with this new feature, #75. Could you try it out and give me some feedback?

**Comment by wyq977** [comment]
I have set the branch to be `remove-color-tag` in submodule but it seems like that the tags are still the same as before

```bash
$ git branch
  master
* remove-color-tag

$ git log
commit 39e8198630263bf669aab021e5b51e286d626aa6 (HEAD -> remove-color-tag, origin/remove-color-tag)
Author: Jimmy Cai <jimmehcai@gmail.com>
Date:   Sun Dec 20 14:40:26 2020 +0100

    refactor(article): remove color tag & add custom category color
    
    closes: https://github.com/CaiJimmy/hugo-theme-stack/issues/71
```

![Screen Shot 2020-12-21 at 10 45 58 PM](https://user-images.githubusercontent.com/27303600/102825238-a7af0d00-43de-11eb-85b7-1b0ba01a959a.png)

**Comment by CaiJimmy** [comment]
Follow this example to set a custom color for each category:

https://github.com/CaiJimmy/hugo-theme-stack/blob/39e8198630263bf669aab021e5b51e286d626aa6/exampleSite/content/categories/Test/_index.md

**Comment by wyq977** [comment]
I changed for each categories and it works 👍 

BTW What is the `   color: "#fff"` for in that case?

**Comment by CaiJimmy** [comment]
> BTW What is the color: "#fff" for in that case?

For text color. By default it's `#fff`, white.

**Comment by wyq977** [comment]
Thx

I guess I can close the issue now

**Comment by CaiJimmy** [comment]
Just leave it open. Once the PR is merged it will be closed automatically.

I think this PR still needs to be improved. Currently, the example site looks a little bit strange to me with those two different color tag:

![image](https://user-images.githubusercontent.com/5889006/102827695-58b7a680-43e3-11eb-9fbc-1c7ddd1bb15c.png)

**Comment by Haebuk** [comment]
hello, is it still problem?
my site's categories have differrent color regardless of same category name.
![image](https://user-images.githubusercontent.com/68543150/194173817-bbfb8337-8400-41ee-9f9e-f7987b098d5a.png)

**Comment by CaiJimmy** [comment]
> hello, is it still problem? my site's categories have differrent color regardless of same category name. ![image](https://user-images.githubusercontent.com/68543150/194173817-bbfb8337-8400-41ee-9f9e-f7987b098d5a.png)

That's expected. You need to manually set colors for each category if you want a fixed color on them.
